#!/bin/sh

logfile=/var/log/relayd

tail -f "$logfile" |
	sed -unE '/\.php/ s/.* (([0-9]{1,3}\.){3}[0-9]{1,3}|([0-9a-f]{1,4}:){7}[0-9a-z]{1,4}) ->.*/\1/p' |
	while read -r ip
	do pfctl -t rate_limit -T add "$ip"
	done
