#!/usr/bin/env perl

use strict;
use warnings;

chroot($ENV{BLIPTOWN_CHROOT});
chdir('/bliptown');

use lib 'lib', 'local/lib';
use Mojolicious::Commands;

Mojolicious::Commands->start_app('Bliptown');
