#!/usr/bin/env perl

use strict;
use warnings;

my $logfile = '/var/log/relayd';
my $ip_re = qr/((?:[0-9]{1,3}\.){3}[0-9]{1,3}|(?:[0-9a-f]{1,4}:){7}[0-9a-z]{1,4}) ->/;

open(my $fh, '<', $logfile);

while (1) {
	while (my $line = <$fh>) {
		next unless $line =~ /\.php/;

		if (my ($ip) = $line =~ $ip_re) {
			system('pfctl', '-t', 'rate_limit', '-T', 'add', $ip);
		}
	}
	sleep 1;
	$fh->clearerr();
}
